const React = require('react-native');
const {Dimensions} = React;
const deviceHeight = Dimensions.get('window').height;
const deviceWidth = Dimensions.get('window').width;

export default {
  field: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  icon: {
    width: 60,
    height: 60,
    borderRadius: 5,
    backgroundColor: '#71b85f',
    justifyContent: 'center',
    alignItems: 'center',
  },
  label: {
    fontSize: 20,
    color: 'rgba(0,0,0,0.4)',
    fontFamily: 'Poppins-SemiBold',
  },
  price: {
    fontSize: 20,
    color: '#000',
    fontFamily: 'Poppins-SemiBold',
  },
  checkOut: {
    fontSize: 22,
    marginTop: 15,
    color: '#71b85f',
    fontFamily: 'Poppins-SemiBold',
  },
  content: {
    width: '78%',
    borderBottomColor: 'rgba(0,0,0,0.15)',
    borderBottomWidth: 1,
  },
  nameField: {
    width: '100%',
    marginTop: 35,
    marginBottom: 20,
  },
  name: {
    width: '100%',
    height: 50,
    padding: 0,
    paddingHorizontal: 15,
    color: '#000',
    borderColor: 'rgba(0,0,0,0.3)',
    borderWidth: 1,
    borderRadius: 5,
    fontSize: 18,
    fontFamily: 'Poppins-SemiBold',
  },
  cardField: {
    width: '100%',
    marginBottom: 20,
    borderColor: 'rgba(0,0,0,0.3)',
    borderWidth: 1,
    borderRadius: 5,
    flexDirection: 'row',
  },
  cardNumber: {
    width: '70%',
    height: 50,
    padding: 0,
    paddingHorizontal: 15,
    color: '#000',
    fontSize: 18,
    fontFamily: 'Poppins-SemiBold',
  },
  month: {
    width: '30%',
    height: 50,
    padding: 0,
    paddingHorizontal: 15,
    color: '#000',
    fontSize: 18,
    fontFamily: 'Poppins-SemiBold',
  },
  cvc: {
    width: '30%',
    height: 50,
    padding: 0,
    paddingHorizontal: 15,
    color: '#000',
    fontSize: 18,
    fontFamily: 'Poppins-SemiBold',
  },
  payBtn: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#71b85f',
    borderRadius: 5,
    marginBottom: 15,
  },
  payBtnText: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'Poppins-SemiBold',
  },
  monthCvv: {
    width: '50%',
    height: 50,
    padding: 0,
    paddingHorizontal: 15,
    color: '#000',
    fontSize: 18,
    fontFamily: 'Poppins-SemiBold',
  },
  cardNumber2: {
    width: '100%',
    height: 50,
    padding: 0,
    paddingHorizontal: 15,
    color: '#000',
    fontSize: 18,
    fontFamily: 'Poppins-SemiBold',
    borderColor: 'rgba(0,0,0,0.3)',
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 20,
  },
  scroll: {
    height: deviceHeight - 84,
  },
};
