export const UPDATE_USER_DATA = "UPDATE_USER_DATA";

// loader data actions
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const UPDATE_USER_DETAILS = "UPDATE USER DETAILS";
export const UPDATE_USER_JOBID = "UPDATE USER JOBID";
export const UPDATE_VIEWPROFILE = "UPDATE_VIEWPROFILE";

export const LOGOUT = "LOGOUT";


// // cart data actions
// export const UPDATE_CART = "UPDATE_CART";
// export const UPDATE_STORE_ID = "UPDATE_STORE_ID";
// export const UPDATE_ORDER_ID = "UPDATE_ORDER_ID";

// export const UPDATE_CARD_TOKEN = "UPDATE CARD TOKEN";
// export const UPDATE_USER_VERIFICATION_STATUS =
//   "UPDATE USER VERIFICATION STATUS";
// export const UPDATE_USER_PAYMENT_METHOD = "UPDATE USER PAYMENT METHOD";

// export const STORE_ACCESS_TOKEN = "STORE ACCESS TOKEN";

// export const UPDATE_STORES = "UPDATE STORES";


 export const CHANGE_APP_OPEN_STATUS = "CHANGE APP OPEN STATUS";
