const React = require('react-native');
const { Dimensions } = React;
const deviceHeight = Dimensions.get('window').height;
const deviceWidth = Dimensions.get('window').width;

export default {
  scroll: {
    height: deviceHeight - 84,
  },
  heading: {
    fontSize: 20,
    color: '#71b85f',
    fontFamily: 'Poppins-SemiBold',
    marginTop: 10,
    marginBottom: 5,
  },
  card: {
    width: '100%',
    paddingHorizontal: 13,
    paddingVertical: 10,
    marginBottom: 15,
    borderRadius: 5,
    borderColor: 'rgba(113,184,95,0.5)',
    borderWidth: 1,
  },
  topSec: {
    width: '100%',
    flexDirection: 'row',
  },
  hdng: {
    width: '70%',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
  },
  timePrice: {
    width: '30%',
    alignItems: 'flex-end',
  },
  timeSec: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  time: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    marginLeft: 5,
    textAlign: 'right',
    color: 'rgba(0,0,0,0.5)',
    paddingTop: 2,
  },
  price: {
    width: '30%',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    paddingLeft: 10,
    textAlign: 'right',
    color: '#71b85f',
  },
  subtitle: {
    width: '100%',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: 'rgba(0,0,0,0.5)',
  },
  wrap: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    marginBottom: 3,
  },
  wrapContent: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 5,
    backgroundColor: '#e5e4e4',
    textAlign: 'center',
    textAlignVertical: 'center',
    color: '#000',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    marginRight: 10,
    marginBottom: 10,
  },
  btnSec: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between'
  },
  btn50: {
    width: '47%',
    height: 40,
    backgroundColor: '#71b85f',
    borderRadius: 40 / 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btn50Text: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    color: '#fff',
    marginLeft: 5,
    paddingTop: 3,
  },
  btn: {
    width: '100%',
    height: 40,
    marginTop: 10,
    backgroundColor: '#71b85f',
    borderRadius: 40 / 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noDataImg: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    height: deviceHeight - 470,
  },
  noDataImgText: {
    marginTop: 15,
    fontSize: 22,
    fontFamily: 'Poppins-SemiBold',
    color: '#71b85f',
  },
  readMore: {
    fontFamily: 'Poppins-SemiBold',
    color: '#71b85f',
    fontSize: 14,
    textAlign: 'right'
  },
  title: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 18,
    marginBottom: 15,
  },
  inputHead: {
    color: 'rgba(59,29,37,0.5)',
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
    marginBottom: 5,
  },
  flastListHead: {
    color: 'rgba(59,29,37,0.5)',
    fontSize: 14,
    marginBottom: 5,
  },
  formrow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'flex-start',
    justifyContent: 'flex-start'
  },
  formGroup: {
    width: '90%',
    marginBottom: 15,
    backgroundColor: '#f8f8f8',
    borderRadius: 4,
    fontSize: 16,
    marginHorizontal: '5%',
    // borderWidth: 1,
    borderColor: 'rgba(59,29,37,0.5)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  // skillView: {
  //     width: '75%',
  //     height: 60,
  //     alignContent: 'center',
  //     display: 'flex',
  //     flexDirection: 'row',
  //     marginHorizontal:'5%',
  //     marginVertical:10,
  // },
  skillView: {
    width: '100%',
    height: 60,
    alignContent: 'center',
    // marginHorizontal: '5%',
    // flexDirection: 'row'
  },
  skillView1: {
    width: '100%',
    height: 60,
    alignContent: 'center',
    display: 'flex',
    flexDirection: 'row',
    // marginHorizontal: '5%',
    marginVertical: 10,
  },
  radio: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    paddingLeft: 0,

  },
  formGroup1: {
    width: '100%',
    height: 50,
    marginBottom: 5,
    backgroundColor: '#f8f8f8',
    borderRadius: 4,
    fontSize: 16,
    borderColor: 'rgba(59,29,37,0.5)',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    textAlignVertical: 'top',
    paddingHorizontal: 15,
    overflow:'hidden'
  },

  formGroup01: {
    width: '100%',
    marginBottom: 15,
    backgroundColor: '#0000',
    borderRadius: 4,
    fontSize: 16,
    // borderWidth: 1,
    borderColor: 'rgba(59,29,37,0.5)',
    flexDirection: 'row',
    // shadowColor: '#000',
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.23,
    // shadowRadius: 2.62,
    // elevation: 4,
    // textAlignVertical: 'top',
  },
  formPicker: {
    width: '80%',
    height: 55,
    backgroundColor: '#f8f8f8',
    borderRadius: 4,
    // borderWidth: 1,
    // borderColor:'rgba(59,29,37,0.5)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    textAlignVertical: 'top',
    overflow: 'hidden'
  },
  formSubGroup1: {
    width: '20%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  formSubGroup2: {
    width: '80%',
  },
  formSubGroup22: {
    width: '100%',
  },
  inputGroup: {
    color: '#3B1D25',
    height: 45,
    fontSize: 15,
  },
  flatList: {
    width: '77%',
    // marginHorizontal: '5%',
    paddingHorizontal: 5,
    backgroundColor: '#f8f8f8',
    borderRadius: 4,
    fontSize: 16,
    borderWidth: 1,
    borderColor: 'rgba(59,29,37,0.5)',
    flexDirection: 'row',
  },
  flatList1: {
    width: '90%',
    marginHorizontal: '5%',
    paddingHorizontal: 5,
    backgroundColor: '#f8f8f8',
    borderRadius: 4,
    fontSize: 16,
    borderWidth: 1,
    borderColor: 'rgba(59,29,37,0.5)',
    flexDirection: 'row',
  },
  details: {
    width: '100%',
    height: 30,
  },
  authBtn: {
    width: '50%',
    marginHorizontal: '8%',
    height: 46,
    borderRadius: 40,
    backgroundColor: '#71b85f',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  authBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  usd: {
    width: '30%',
    backgroundColor: '#fff',
    borderRadius: 4,
    fontSize: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: 'rgba(59,29,37,0.5)',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,

  },
  skillTab: {
    //width: '40%',
    backgroundColor: '#E4E4E4',
    paddingHorizontal: 10,
    height: 40,
    borderRadius: 40 / 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 5,
    marginRight: 10,
    flexDirection: 'row',
  },
  marginRight3: {
    margin: 5,
  },
  skillText: {
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    color: '#000',
    marginLeft: 3,
    textAlign: "center",
  },
  actionEdtBtn: {
    flexDirection: 'row',
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 50
  },
  errorText: {
    width: '100%',
    color: '#fc0303',
  },
  modalContent: {
    width: '90%',
    height: deviceHeight - 200,
    // paddingVertical: 30,
    // paddingHorizontal: 25,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    alignItems: 'center',
  },
  modalContent2: {
    width: '90%',
    minHeight: 200,
    maxHeight: deviceHeight - 200,
    // paddingVertical: 30,
    // paddingHorizontal: 25,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    alignItems: 'center',
  },
  modalCross: {
    position: 'absolute',
    top: 0,
    right: 0,
  },
};
