export default EndPoint = {
  BASE_URL: 'https://api.connectbud.com/',
  LOGIN: 'auth/login',
  EmployerSignUp:'auth/register_recruiter',
  FreelancerSignUp:'auth/signup',
  ValidateCollegeEmail:'fetchemail',
  ExpertProfile : "expertProfile/",
  FetchSkills:'keyskill/recruiter',
  Location:'keyskill/',
  PostJob:'recruiter_job_post',
  FetchCategory: 'Tags/list/',
  CategorySubmit: 'categorised_skill',
  ChildSkillSubmit: 'freelancer_tags',
  FetchSubjectSkills : 'fetch_skills',
  tutorhomework: 'tutorhomework',
  FreelancerJob:'freelancerJob',
  JobMail:'jobmail',
  RecrutierFeedPage:'recruiter_feedpage',
  RecrutierIntialSearch:'recruiter_initalsearch',
  FilterSkill:'categorised_skill',
  FetchTutorCategory: 'keyskill/tutor',
  FetchProjectCategory: 'keyskill/freelancer',
  JobSummary: 'expert_jobsummary',
  Four: '/course/four',
  Ten: '/course/ten',
  CourseSubmit: 'course_submit',
  FetchMilestones: 'fetchmilestones',
  PLACEHOLDER_SQUARE_IMAGE: require('../assets/images/userPro.jpg'),
  FreelancerJobList: 'freelancerJobList',
  JobRelatedCandidates: 'job_related_candidates',
  InvitationMail: 'invitation_mail',
  JobDetails: 'job_details/',
  AddSkill: 'keyskill/else',
  RecruiterProfile: 'recruiterProfile/',
  PostedJob: 'my_postedjob',
  UPDATE_ID:'updateid',
  SENDSMS:'sendsms',
  VALIDATE_OTP:'validate_otp',
  SaveProfileImage: 'SaveProfileImage',
  SaveCoverImage: 'SaveCoverImage',
  QuestionAnswer: 'Questions/MyQuestions',
  FetchQuestion: 'Questions/fetchQuestion/',
  FeedQuestions: 'Questions/feedQuestions',
};
export const BASE_URL ="https://api.connectbud.com/"   //do not remove
