export default EndPoint = {
  BASE_URL: 'https://api.connectbud.com/',
  LOGIN: 'auth/login',
  EmployerSignUp:'auth/register_recruiter',
  FreelancerSignUp:'auth/signup',
  ValidateCollegeEmail:'fetchemail',
  ExpertProfile : "expertProfile/",
  FetchSkills:'keyskill/recruiter',
  Location:'keyskill/',
  PostJob:'recruiter_job_post',
  FetchCategory: 'Tags/list/',
  CategorySubmit: 'categorised_skill',
  ChildSkillSubmit: 'freelancer_tags',
  FetchSubjectSkills : 'fetch_skills',
  tutorhomework: 'tutorhomework',
  FreelancerJob:'freelancerJob',
  JobMail:'jobmail',
  FetchTutorCategory: 'keyskill/tutor',
  FetchProjectCategory: 'keyskill/freelancer',
  JobSummary: 'expert_jobsummary',
  Four: '/course/four',
  Ten: '/course/ten',
  CourseSubmit: 'course_submit',

};
export const BASE_URL ="https://api.connectbud.com/"   //do not remove
