export const timeZone = [
    { zonevalue: "Select timezone" },
    { zonevalue: "(GMT-11:00) Niue Time" },
    { zonevalue: "(GMT-11:00) Samoa Standard Time" },
    { zonevalue: "(GMT-10:00) Cook Islands Standard Time" },
    { zonevalue: "(GMT-10:00) Hawaii-Aleutian Standard Time" },
    { zonevalue: "(GMT-10:00) Hawaii-Aleutian Time" },
    { zonevalue: "(GMT-10:00) Tahiti Time" },
    { zonevalue: "(GMT-09:30) Marquesas Time" },
    { zonevalue: "(GMT-09:00) Alaska Time - Anchorage" },
    { zonevalue: "(GMT-09:00) Alaska Time - Juneau" },
    { zonevalue: "(GMT-09:00) Alaska Time - Nome" },
    { zonevalue: "(GMT-09:00) Alaska Time - Sitka" },
    { zonevalue: "(GMT-09:00) Alaska Time - Yakutat" },
    { zonevalue: "(GMT-09:00) Gambier Time" },
    { zonevalue: "(GMT-08:00) Pacific Time - Dawson" },
    { zonevalue: "(GMT-08:00) Pacific Time - Los Angeles" },
    { zonevalue: "(GMT-08:00) Pacific Time - Metlakatla" },
    { zonevalue: "(GMT-08:00) Pacific Time - Tijuana" },
    { zonevalue: "(GMT-08:00) Pacific Time - Vancouver" },
    { zonevalue: "(GMT-08:00) Pacific Time - Whitehorse" },
    { zonevalue: "(GMT-08:00) Pitcairn Time" },
    { zonevalue: "(GMT-07:00) Mexican Pacific Standard Time" },
    { zonevalue: "(GMT-07:00) Mexican Pacific Time - Chihuahua" },
    { zonevalue: "(GMT-07:00) Mexican Pacific Time - Mazatlan" },
    { zonevalue: "(GMT-07:00) Mountain Standard Time - Creston" },
    { zonevalue: "(GMT-07:00) Mountain Standard Time - Dawson Creek" },
    { zonevalue: "(GMT-07:00) Mountain Standard Time - Fort Nelson" },
    { zonevalue: "(GMT-07:00) Mountain Standard Time - Phoenix" },
    { zonevalue: "(GMT-07:00) Mountain Time - Boise" },
    { zonevalue: "(GMT-07:00) Mountain Time - Cambridge Bay" },
    { zonevalue: "(GMT-07:00) Mountain Time - Denver" },
    { zonevalue: "(GMT-07:00) Mountain Time - Edmonton" },
    { zonevalue: "(GMT-07:00) Mountain Time - Inuvik" },
    { zonevalue: "(GMT-07:00) Mountain Time - Ojinaga" },
    { zonevalue: "(GMT-07:00) Mountain Time - Yellowknife" },
    { zonevalue: "(GMT-06:00) Central Standard Time - Belize" },
    { zonevalue: "(GMT-06:00) Central Standard Time - Costa Rica" },
    { zonevalue: "(GMT-06:00) Central Standard Time - El Salvador" },
    { zonevalue: "(GMT-06:00) Central Standard Time - Guatemala" },
    { zonevalue: "(GMT-06:00) Central Standard Time - Managua" },
    { zonevalue: "(GMT-06:00) Central Standard Time - Regina" },
    { zonevalue: "(GMT-06:00) Central Standard Time - Swift Current" },
    { zonevalue: "(GMT-06:00) Central Standard Time - Tegucigalpa" },
    { zonevalue: "(GMT-06:00) Central Time - Bahia Banderas" },
    { zonevalue: "(GMT-06:00) Central Time - Beulah, North Dakota" },
    { zonevalue: "(GMT-06:00) Central Time - Center, North Dakota" },
    { zonevalue: "(GMT-06:00) Central Time - Chicago" },
    { zonevalue: "(GMT-06:00) Central Time - Knox, Indiana" },
    { zonevalue: "(GMT-06:00) Central Time - Matamoros" },
    { zonevalue: "(GMT-06:00) Central Time - Menominee" },
    { zonevalue: "(GMT-06:00) Central Time - Merida" },
    { zonevalue: "(GMT-06:00) Central Time - Mexico City" },
    { zonevalue: "(GMT-06:00) Central Time - Monterrey" },
    { zonevalue: "(GMT-06:00) Central Time - New Salem, North Dakota" },
    { zonevalue: "(GMT-06:00) Central Time - Rainy River" },
    { zonevalue: "(GMT-06:00) Central Time - Rankin Inlet" },
    { zonevalue: "(GMT-06:00) Central Time - Resolute" },
    { zonevalue: "(GMT-06:00) Central Time - Tell City, Indiana" },
    { zonevalue: "(GMT-06:00) Central Time - Winnipeg" },
    { zonevalue: "(GMT-06:00) Galapagos Time" },
    { zonevalue: "(GMT-05:00) Acre Standard Time - Eirunepe" },
    { zonevalue: "(GMT-05:00) Acre Standard Time - Rio Branco" },
    { zonevalue: "(GMT-05:00) Colombia Standard Time" },
    { zonevalue: "(GMT-05:00) Cuba Time" },
    { zonevalue: "(GMT-05:00) Easter Island Time" },
    { zonevalue: "(GMT-05:00) Eastern Standard Time - Atikokan" },
    { zonevalue: "(GMT-05:00) Eastern Standard Time - Cancun" },
    { zonevalue: "(GMT-05:00) Eastern Standard Time - Jamaica" },
    { zonevalue: "(GMT-05:00) Eastern Standard Time - Panama" },
    { zonevalue: "(GMT-05:00) Eastern Time - Detroit" },
    { zonevalue: "(GMT-05:00) Eastern Time - Grand Turk" },
    { zonevalue: "(GMT-05:00) Eastern Time - Indianapolis" },
    { zonevalue: "(GMT-05:00) Eastern Time - Iqaluit" },
    { zonevalue: "(GMT-05:00) Eastern Time - Louisville" },
    { zonevalue: "(GMT-05:00) Eastern Time - Marengo, Indiana" },
    { zonevalue: "(GMT-05:00) Eastern Time - Monticello, Kentucky" },
    { zonevalue: "(GMT-05:00) Eastern Time - Nassau" },
    { zonevalue: "(GMT-05:00) Eastern Time - New York" },
    { zonevalue: "(GMT-05:00) Eastern Time - Nipigon" },
    { zonevalue: "(GMT-05:00) Eastern Time - Pangnirtung" },
    { zonevalue: "(GMT-05:00) Eastern Time - Petersburg, Indiana" },
    { zonevalue: "(GMT-05:00) Eastern Time - Port-au-Prince" },
    { zonevalue: "(GMT-05:00) Eastern Time - Thunder Bay" },
    { zonevalue: "(GMT-05:00) Eastern Time - Toronto" },
    { zonevalue: "(GMT-05:00) Eastern Time - Vevay, Indiana" },
    { zonevalue: "(GMT-05:00) Eastern Time - Vincennes, Indiana" },
    { zonevalue: "(GMT-05:00) Eastern Time - Winamac, Indiana" },
    { zonevalue: "(GMT-05:00) Ecuador Time" },
    { zonevalue: "(GMT-05:00) Peru Standard Time" },
    { zonevalue: "(GMT-04:00) Amazon Standard Time - Boa Vista" },
    { zonevalue: "(GMT-04:00) Amazon Standard Time - Manaus" },
    { zonevalue: "(GMT-04:00) Amazon Standard Time - Porto Velho" },
    { zonevalue: "(GMT-04:00) Atlantic Standard Time - Barbados" },
    { zonevalue: "(GMT-04:00) Atlantic Standard Time - Blanc-Sablon" },
    { zonevalue: "(GMT-04:00) Atlantic Standard Time - Curaçao" },
    { zonevalue: "(GMT-04:00) Atlantic Standard Time - Martinique" },
    { zonevalue: "(GMT-04:00) Atlantic Standard Time - Port of Spain" },
    { zonevalue: "(GMT-04:00) Atlantic Standard Time - Puerto Rico" },
    { zonevalue: "(GMT-04:00) Atlantic Standard Time - Santo Domingo" },
    { zonevalue: "(GMT-04:00) Atlantic Time - Bermuda" },
    { zonevalue: "(GMT-04:00) Atlantic Time - Glace Bay" },
    { zonevalue: "(GMT-04:00) Atlantic Time - Goose Bay" },
    { zonevalue: "(GMT-04:00) Atlantic Time - Halifax" },
    { zonevalue: "(GMT-04:00) Atlantic Time - Moncton" },
    { zonevalue: "(GMT-04:00) Atlantic Time - Thule" },
    { zonevalue: "(GMT-04:00) Bolivia Time" },
    { zonevalue: "(GMT-04:00) Guyana Time" },
    { zonevalue: "(GMT-04:00) Venezuela Time" },
    { zonevalue: "(GMT-03:30) Newfoundland Time" },
    { zonevalue: "(GMT-03:00) Amazon Time (Campo Grande)" },
    { zonevalue: "(GMT-03:00) Amazon Time (Cuiaba)" },
    { zonevalue: "(GMT-03:00) Argentina Standard Time - Buenos Aires" },
    { zonevalue: "(GMT-03:00) Argentina Standard Time - Catamarca" },
    { zonevalue: "(GMT-03:00) Argentina Standard Time - Cordoba" },
    { zonevalue: "(GMT-03:00) Argentina Standard Time - Jujuy" },
    { zonevalue: "(GMT-03:00) Argentina Standard Time - La Rioja" },
    { zonevalue: "(GMT-03:00) Argentina Standard Time - Mendoza" },
    { zonevalue: "(GMT-03:00) Argentina Standard Time - Rio Gallegos" },
    { zonevalue: "(GMT-03:00) Argentina Standard Time - Salta" },
    { zonevalue: "(GMT-03:00) Argentina Standard Time - San Juan" },
    { zonevalue: "(GMT-03:00) Argentina Standard Time - Tucuman" },
    { zonevalue: "(GMT-03:00) Argentina Standard Time - Ushuaia" },
    { zonevalue: "(GMT-03:00) Brasilia Standard Time - Araguaina" },
    { zonevalue: "(GMT-03:00) Brasilia Standard Time - Bahia" },
    { zonevalue: "(GMT-03:00) Brasilia Standard Time - Belem" },
    { zonevalue: "(GMT-03:00) Brasilia Standard Time - Fortaleza" },
    { zonevalue: "(GMT-03:00) Brasilia Standard Time - Maceio" },
    { zonevalue: "(GMT-03:00) Brasilia Standard Time - Recife" },
    { zonevalue: "(GMT-03:00) Brasilia Standard Time - Santarem" },
    { zonevalue: "(GMT-03:00) Chile Time" },
    { zonevalue: "(GMT-03:00) Falkland Islands Standard Time" },
    { zonevalue: "(GMT-03:00) French Guiana Time" },
    { zonevalue: "(GMT-03:00) Palmer Time" },
    { zonevalue: "(GMT-03:00) Paraguay Time" },
    { zonevalue: "(GMT-03:00) Punta Arenas Time" },
    { zonevalue: "(GMT-03:00) Rothera Time" },
    { zonevalue: "(GMT-03:00) St. Pierre & Miquelon Time" },
    { zonevalue: "(GMT-03:00) Suriname Time" },
    { zonevalue: "(GMT-03:00) Uruguay Standard Time" },
    { zonevalue: "(GMT-03:00) West Greenland Time" },
    { zonevalue: "(GMT-03:00) Western Argentina Standard Time" },
    { zonevalue: "(GMT-02:00) Brasilia Time" },
    { zonevalue: "(GMT-02:00) Fernando de Noronha Standard Time" },
    { zonevalue: "(GMT-02:00) South Georgia Time" },
    { zonevalue: "(GMT-01:00) Azores Time" },
    { zonevalue: "(GMT-01:00) Cape Verde Standard Time" },
    { zonevalue: "(GMT-01:00) East Greenland Time" },
    { zonevalue: "(GMT+00:00) Coordinated Universal Time" },
    { zonevalue: "(GMT+00:00) Greenwich Mean Time" },
    { zonevalue: "(GMT+00:00) Greenwich Mean Time - Abidjan" },
    { zonevalue: "(GMT+00:00) Greenwich Mean Time - Accra" },
    { zonevalue: "(GMT+00:00) Greenwich Mean Time - Bissau" },
    { zonevalue: "(GMT+00:00) Greenwich Mean Time - Danmarkshavn" },
    { zonevalue: "(GMT+00:00) Greenwich Mean Time - Monrovia" },
    { zonevalue: "(GMT+00:00) Greenwich Mean Time - Reykjavik" },
    { zonevalue: "(GMT+00:00) Greenwich Mean Time - São Tomé" },
    { zonevalue: "(GMT+00:00) Ireland Time" },
    { zonevalue: "(GMT+00:00) Troll Time" },
    { zonevalue: "(GMT+00:00) United Kingdom Time" },
    { zonevalue: "(GMT+00:00) Western European Time - Canary" },
    { zonevalue: "(GMT+00:00) Western European Time - Faroe" },
    { zonevalue: "(GMT+00:00) Western European Time - Lisbon" },
    { zonevalue: "(GMT+00:00) Western European Time - Madeira" },
    { zonevalue: "(GMT+01:00) Central European Standard Time - Algiers" },
    { zonevalue: "(GMT+01:00) Central European Standard Time - Tunis" },
    { zonevalue: "(GMT+01:00) Central European Time - Amsterdam" },
    { zonevalue: "(GMT+01:00) Central European Time - Andorra" },
    { zonevalue: "(GMT+01:00) Central European Time - Belgrade" },
    { zonevalue: "(GMT+01:00) Central European Time - Berlin" },
    { zonevalue: "(GMT+01:00) Central European Time - Brussels" },
    { zonevalue: "(GMT+01:00) Central European Time - Budapest" },
    { zonevalue: "(GMT+01:00) Central European Time - Ceuta" },
    { zonevalue: "(GMT+01:00) Central European Time - Copenhagen" },
    { zonevalue: "(GMT+01:00) Central European Time - Gibraltar" },
    { zonevalue: "(GMT+01:00) Central European Time - Luxembourg" },
    { zonevalue: "(GMT+01:00) Central European Time - Madrid" },
    { zonevalue: "(GMT+01:00) Central European Time - Malta" },
    { zonevalue: "(GMT+01:00) Central European Time - Monaco" },
    { zonevalue: "(GMT+01:00) Central European Time - Oslo" },
    { zonevalue: "(GMT+01:00) Central European Time - Paris" },
    { zonevalue: "(GMT+01:00) Central European Time - Prague" },
    { zonevalue: "(GMT+01:00) Central European Time - Rome" },
    { zonevalue: "(GMT+01:00) Central European Time - Stockholm" },
    { zonevalue: "(GMT+01:00) Central European Time - Tirane" },
    { zonevalue: "(GMT+01:00) Central European Time - Vienna" },
    { zonevalue: "(GMT+01:00) Central European Time - Warsaw" },
    { zonevalue: "(GMT+01:00) Central European Time - Zurich" },
    { zonevalue: "(GMT+01:00) Morocco Time" },
    { zonevalue: "(GMT+01:00) West Africa Standard Time - Lagos" },
    { zonevalue: "(GMT+01:00) West Africa Standard Time - Ndjamena" },
    { zonevalue: "(GMT+01:00) Western Sahara Time" },
    { zonevalue: "(GMT+02:00) Central Africa Time - Khartoum" },
    { zonevalue: "(GMT+02:00) Central Africa Time - Maputo" },
    { zonevalue: "(GMT+02:00) Central Africa Time - Windhoek" },
    { zonevalue: "(GMT+02:00) Eastern European Standard Time - Cairo" },
    { zonevalue: "(GMT+02:00) Eastern European Standard Time - Kaliningrad" },
    { zonevalue: "(GMT+02:00) Eastern European Standard Time - Tripoli" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Amman" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Athens" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Beirut" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Bucharest" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Chisinau" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Damascus" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Gaza" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Hebron" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Helsinki" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Kiev" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Nicosia" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Riga" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Sofia" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Tallinn" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Uzhhorod" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Vilnius" },
    { zonevalue: "(GMT+02:00) Eastern European Time - Zaporozhye" },
    { zonevalue: "(GMT+02:00) Famagusta Time" },
    { zonevalue: "(GMT+02:00) Israel Time" },
    { zonevalue: "(GMT+02:00) South Africa Standard Time" },
    { zonevalue: "(GMT+03:00) Arabian Standard Time - Baghdad" },
    { zonevalue: "(GMT+03:00) Arabian Standard Time - Qatar" },
    { zonevalue: "(GMT+03:00) Arabian Standard Time - Riyadh" },
    { zonevalue: "(GMT+03:00) East Africa Time - Juba" },
    { zonevalue: "(GMT+03:00) East Africa Time - Nairobi" },
    { zonevalue: "(GMT+03:00) Kirov Time" },
    { zonevalue: "(GMT+03:00) Moscow Standard Time - Minsk" },
    { zonevalue: "(GMT+03:00) Moscow Standard Time - Moscow" },
    { zonevalue: "(GMT+03:00) Moscow Standard Time - Simferopol" },
    { zonevalue: "(GMT+03:00) Syowa Time" },
    { zonevalue: "(GMT+03:00) Turkey Time" },
    { zonevalue: "(GMT+03:30) Iran Time" },
    { zonevalue: "(GMT+04:00) Armenia Standard Time" },
    { zonevalue: "(GMT+04:00) Astrakhan Time" },
    { zonevalue: "(GMT+04:00) Azerbaijan Standard Time" },
    { zonevalue: "(GMT+04:00) Georgia Standard Time" },
    { zonevalue: "(GMT+04:00) Gulf Standard Time" },
    { zonevalue: "(GMT+04:00) Mauritius Standard Time" },
    { zonevalue: "(GMT+04:00) Réunion Time" },
    { zonevalue: "(GMT+04:00) Samara Standard Time" },
    { zonevalue: "(GMT+04:00) Saratov Time" },
    { zonevalue: "(GMT+04:00) Seychelles Time" },
    { zonevalue: "(GMT+04:00) Ulyanovsk Time" },
    { zonevalue: "(GMT+04:00) Volgograd Standard Time" },
    { zonevalue: "(GMT+04:30) Afghanistan Time" },
    { zonevalue: "(GMT+05:00) French Southern & Antarctic Time" },
    { zonevalue: "(GMT+05:00) Maldives Time" },
    { zonevalue: "(GMT+05:00) Mawson Time" },
    { zonevalue: "(GMT+05:00) Pakistan Standard Time" },
    { zonevalue: "(GMT+05:00) Tajikistan Time" },
    { zonevalue: "(GMT+05:00) Turkmenistan Standard Time" },
    { zonevalue: "(GMT+05:00) Uzbekistan Standard Time - Samarkand" },
    { zonevalue: "(GMT+05:00) Uzbekistan Standard Time - Tashkent" },
    { zonevalue: "(GMT+05:00) West Kazakhstan Time - Aqtau" },
    { zonevalue: "(GMT+05:00) West Kazakhstan Time - Aqtobe" },
    { zonevalue: "(GMT+05:00) West Kazakhstan Time - Atyrau" },
    { zonevalue: "(GMT+05:00) West Kazakhstan Time - Oral" },
    { zonevalue: "(GMT+05:00) West Kazakhstan Time - Qyzylorda" },
    { zonevalue: "(GMT+05:00) Yekaterinburg Standard Time" },
    { zonevalue: "(GMT+05:30) India Standard Time - Colombo" },
    { zonevalue: "(GMT+05:30) India Standard Time - Kolkata" },
    { zonevalue: "(GMT+05:45) Nepal Time" },
    { zonevalue: "(GMT+06:00) Bangladesh Standard Time" },
    { zonevalue: "(GMT+06:00) Bhutan Time" },
    { zonevalue: "(GMT+06:00) East Kazakhstan Time - Almaty" },
    { zonevalue: "(GMT+06:00) East Kazakhstan Time - Qostanay" },
    { zonevalue: "(GMT+06:00) Indian Ocean Time" },
    { zonevalue: "(GMT+06:00) Kyrgyzstan Time" },
    { zonevalue: "(GMT+06:00) Omsk Standard Time" },
    { zonevalue: "(GMT+06:00) Urumqi Time" },
    { zonevalue: "(GMT+06:00) Vostok Time" },
    { zonevalue: "(GMT+06:30) Cocos Islands Time" },
    { zonevalue: "(GMT+06:30) Myanmar Time" },
    { zonevalue: "(GMT+07:00) Barnaul Time" },
    { zonevalue: "(GMT+07:00) Christmas Island Time" },
    { zonevalue: "(GMT+07:00) Davis Time" },
    { zonevalue: "(GMT+07:00) Hovd Standard Time" },
    { zonevalue: "(GMT+07:00) Indochina Time - Bangkok" },
    { zonevalue: "(GMT+07:00) Indochina Time - Ho Chi Minh City" },
    { zonevalue: "(GMT+07:00) Krasnoyarsk Standard Time - Krasnoyarsk" },
    { zonevalue: "(GMT+07:00) Krasnoyarsk Standard Time - Novokuznetsk" },
    { zonevalue: "(GMT+07:00) Novosibirsk Standard Time" },
    { zonevalue: "(GMT+07:00) Tomsk Time" },
    { zonevalue: "(GMT+07:00) Western Indonesia Time - Jakarta" },
    { zonevalue: "(GMT+07:00) Western Indonesia Time - Pontianak" },
    { zonevalue: "(GMT+08:00) Australian Western Standard Time - Casey" },
    { zonevalue: "(GMT+08:00) Australian Western Standard Time - Perth" },
    { zonevalue: "(GMT+08:00) Brunei Darussalam Time" },
    { zonevalue: "(GMT+08:00) Central Indonesia Time" },
    { zonevalue: "(GMT+08:00) China Standard Time - Macau" },
    { zonevalue: "(GMT+08:00) China Standard Time - Shanghai" },
    { zonevalue: "(GMT+08:00) Choibalsan Standard Time" },
    { zonevalue: "(GMT+08:00) Hong Kong Standard Time" },
    { zonevalue: "(GMT+08:00) Irkutsk Standard Time" },
    { zonevalue: "(GMT+08:00) Malaysia Time - Kuala Lumpur" },
    { zonevalue: "(GMT+08:00) Malaysia Time - Kuching" },
    { zonevalue: "(GMT+08:00) Philippine Standard Time" },
    { zonevalue: "(GMT+08:00) Singapore Standard Time" },
    { zonevalue: "(GMT+08:00) Taipei Standard Time" },
    { zonevalue: "(GMT+08:00) Ulaanbaatar Standard Time" },
    { zonevalue: "(GMT+08:45) Australian Central Western Standard Time" },
    { zonevalue: "(GMT+09:00) East Timor Time" },
    { zonevalue: "(GMT+09:00) Eastern Indonesia Time" },
    { zonevalue: "(GMT+09:00) Japan Standard Time" },
    { zonevalue: "(GMT+09:00) Korean Standard Time - Pyongyang" },
    { zonevalue: "(GMT+09:00) Korean Standard Time - Seoul" },
    { zonevalue: "(GMT+09:00) Palau Time" },
    { zonevalue: "(GMT+09:00) Yakutsk Standard Time - Chita" },
    { zonevalue: "(GMT+09:00) Yakutsk Standard Time - Khandyga" },
    { zonevalue: "(GMT+09:00) Yakutsk Standard Time - Yakutsk" },
    { zonevalue: "(GMT+09:30) Australian Central Standard Time" },
    { zonevalue: "(GMT+10:00) Australian Eastern Standard Time - Brisbane" },
    { zonevalue: "(GMT+10:00) Australian Eastern Standard Time - Lindeman" },
    { zonevalue: "(GMT+10:00) Chamorro Standard Time" },
    { zonevalue: "(GMT+10:00) Chuuk Time" },
    { zonevalue: "(GMT+10:00) Dumont-d’Urville Time" },
    { zonevalue: "(GMT+10:00) Papua New Guinea Time" },
    { zonevalue: "(GMT+10:00) Vladivostok Standard Time - Ust-Nera" },
    { zonevalue: "(GMT+10:00) Vladivostok Standard Time - Vladivostok" },
    { zonevalue: "(GMT+10:30) Central Australia Time - Adelaide" },
    { zonevalue: "(GMT+10:30) Central Australia Time - Broken Hill" },
    { zonevalue: "(GMT+11:00) Bougainville Time" },
    { zonevalue: "(GMT+11:00) Eastern Australia Time - Currie" },
    { zonevalue: "(GMT+11:00) Eastern Australia Time - Hobart" },
    { zonevalue: "(GMT+11:00) Eastern Australia Time - Melbourne" },
    { zonevalue: "(GMT+11:00) Eastern Australia Time - Sydney" },
    { zonevalue: "(GMT+11:00) Kosrae Time" },
    { zonevalue: "(GMT+11:00) Lord Howe Time" },
    { zonevalue: "(GMT+11:00) Macquarie Island Time" },
    { zonevalue: "(GMT+11:00) Magadan Standard Time" },
    { zonevalue: "(GMT+11:00) New Caledonia Standard Time" },
    { zonevalue: "(GMT+11:00) Norfolk Island Time" },
    { zonevalue: "(GMT+11:00) Ponape Time" },
    { zonevalue: "(GMT+11:00) Sakhalin Standard Time" },
    { zonevalue: "(GMT+11:00) Solomon Islands Time" },
    { zonevalue: "(GMT+11:00) Srednekolymsk Time" },
    { zonevalue: "(GMT+11:00) Vanuatu Standard Time" },
    { zonevalue: "(GMT+12:00) Anadyr Standard Time" },
    { zonevalue: "(GMT+12:00) Fiji Time" },
    { zonevalue: "(GMT+12:00) Gilbert Islands Time" },
    { zonevalue: "(GMT+12:00) Marshall Islands Time - Kwajalein" },
    { zonevalue: "(GMT+12:00) Marshall Islands Time - Majuro" },
    { zonevalue: "(GMT+12:00) Nauru Time" },
    { zonevalue: "(GMT+12:00) Petropavlovsk-Kamchatski Standard Time" },
    { zonevalue: "(GMT+12:00) Tuvalu Time" },
    { zonevalue: "(GMT+12:00) Wake Island Time" },
    { zonevalue: "(GMT+12:00) Wallis & Futuna Time" },
    { zonevalue: "(GMT+13:00) New Zealand Time" },
    { zonevalue: "(GMT+13:00) Phoenix Islands Time" },
    { zonevalue: "(GMT+13:00) Tokelau Time" },
    { zonevalue: "(GMT+13:00) Tonga Standard Time" },
    { zonevalue: "(GMT+13:45) Chatham Time" },
    { zonevalue: "(GMT+14:00) Apia Time" },
    { zonevalue: "(GMT+14:00) Line Islands Time" },
]