export default {
  imgSec: {
    width: 90,
    height: 90,
    marginTop: 20,
    borderRadius: 90 / 2,
    overflow: 'hidden',
  },
  topSec: {
    alignItems: 'center',
    padding: 20,
    //borderBottomColor: 'rgba(255,255,255,0.3)',
    //borderBottomWidth: 1,
  },
  userDetails: {
    marginTop: 10,
    alignItems: 'center',
  },
  name: {
    fontFamily: 'Poppins-SemiBold',
    color: '#fff',
    fontSize: 20,
    textAlign: 'center',
  },
  slogan: {
    fontFamily: 'Poppins-Regular',
    color: '#fff',
    fontSize: 18,
    textAlign: 'center',
    marginTop: -7,
  },
  menuOptn: {
    width: '100%',
    height: 60,
    paddingHorizontal: '10%',
    alignItems: 'center',
    borderBottomColor: 'rgba(255,255,255,0.2)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  menuOptn3: {
    width: '100%',
    // height: 60,
    paddingHorizontal: '5%',
    paddingVertical: 7,
    alignItems: 'center',
    borderBottomColor: 'rgba(255,255,255,0.2)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  menuOptnText: {
    width: '80%',
    fontFamily: 'Poppins-Regular',
    color: '#fff',
    fontSize: 20,
    marginLeft: 10,
    marginTop: 5,
  },
  menuOptn2: {
    width: '100%',
    height: 60,
    paddingHorizontal: '10%',
    alignItems: 'center',
    borderBottomColor: 'rgba(255,255,255,0.2)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
  },
  menuOptnText2: {
    width: '80%',
    fontFamily: 'Poppins-Regular',
    color: '#71b85f',
    fontSize: 20,
    marginLeft: 10,
    marginTop: 5,
  },
  socialIcon: {
    width: '100%',
    paddingHorizontal: '8%',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    paddingBottom: 5,
  },
  socialText: {
    fontFamily: 'Poppins-SemiBold',
    color: '#fff',
    fontSize: 20,
    textAlign: 'center',
  },
  socialSec: {
    height: 100,
    justifyContent: 'center',
    borderTopColor: 'rgba(255,255,255,0.2)',
    borderTopWidth: 1,
  },
  collapsePos: {
    position: 'absolute',
    right: 25,
  },
  sideLogo: {
    width: 160,
    height: 40,
    marginBottom: 40,
    alignSelf: 'center'
  },
};
